In [15]:
!pip install --upgrade pip

Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  WARNING: The scripts pip, pip3, pip3.10 and pip3.8 are installed in '/workspace/.pyenv_mirror/user/current/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.3.1

In [16]:

%pip install wheel

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
Note: you may need to restart the kernel to use updated packages.

In [17]:

%pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (2.7.1)
Requirement already satisfied: dill<0.3.7 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (0.3.6)
Requirement already satisfied: xxhash in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (3.1.0)
Requirement already satisfied: tqdm>=4.62.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (4.64.1)
Requirement already satisfied: aiohttp in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (3.8.3)
Requirement already satisfied: responses<0.19 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (0.18.0)
Requirement already satisfied: requests>=2.19.0 in /usr/lib/python3/dist-packages (from datasets) (2.22.0)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (2022.11.0)
Requirement already satisfied: packaging in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (22.0)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (0.11.1)
Requirement already satisfied: pyarrow>=6.0.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (10.0.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from datasets) (5.3.1)
Requirement already satisfied: pandas in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (1.5.2)
Requirement already satisfied: numpy>=1.17 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (1.23.5)
Requirement already satisfied: multiprocess in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from datasets) (0.70.14)
Requirement already satisfied: frozenlist>=1.1.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (2.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (1.8.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp->datasets) (6.0.3)
Requirement already satisfied: filelock in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (3.8.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (4.4.0)
Requirement already satisfied: urllib3>=1.25.10 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from responses<0.19->datasets) (1.26.13)
Requirement already satisfied: python-dateutil>=2.8.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pandas->datasets) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.14.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->datasets) (2.8)
Note: you may need to restart the kernel to use updated packages.

In [18]:
%pip install --upgrade simplet5

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: simplet5 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (0.1.4)
Requirement already satisfied: pandas in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (1.5.2)
Requirement already satisfied: transformers==4.16.2 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (4.16.2)
Requirement already satisfied: sentencepiece in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (0.1.97)
Requirement already satisfied: torch!=1.8.0,>=1.7.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (1.13.0)
Requirement already satisfied: pytorch-lightning==1.5.10 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (1.5.10)
Requirement already satisfied: numpy in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from simplet5) (1.23.5)
Requirement already satisfied: future>=0.17.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (0.18.2)
Requirement already satisfied: PyYAML>=5.1 in /usr/lib/python3/dist-packages (from pytorch-lightning==1.5.10->simplet5) (5.3.1)
Requirement already satisfied: torchmetrics>=0.4.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (0.11.0)
Requirement already satisfied: packaging>=17.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (22.0)
Requirement already satisfied: setuptools==59.5.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (59.5.0)
Requirement already satisfied: tqdm>=4.41.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (4.64.1)
Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (2022.11.0)
Requirement already satisfied: typing-extensions in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (4.4.0)
Requirement already satisfied: pyDeprecate==0.3.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (0.3.1)
Requirement already satisfied: tensorboard>=2.2.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pytorch-lightning==1.5.10->simplet5) (2.11.0)
Requirement already satisfied: sacremoses in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from transformers==4.16.2->simplet5) (0.0.53)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from transformers==4.16.2->simplet5) (2.22.0)
Requirement already satisfied: filelock in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from transformers==4.16.2->simplet5) (3.8.2)
Requirement already satisfied: tokenizers!=0.11.3,>=0.10.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from transformers==4.16.2->simplet5) (0.13.2)
Requirement already satisfied: regex!=2019.12.17 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from transformers==4.16.2->simplet5) (2022.10.31)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from transformers==4.16.2->simplet5) (0.11.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from torch!=1.8.0,>=1.7.0->simplet5) (11.7.99)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from torch!=1.8.0,>=1.7.0->simplet5) (11.10.3.66)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from torch!=1.8.0,>=1.7.0->simplet5) (8.5.0.96)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from torch!=1.8.0,>=1.7.0->simplet5) (11.7.99)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch!=1.8.0,>=1.7.0->simplet5) (0.34.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pandas->simplet5) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pandas->simplet5) (2022.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (3.8.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->simplet5) (1.14.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (1.8.1)
Requirement already satisfied: absl-py>=0.4 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (1.3.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (0.4.6)
Requirement already satisfied: werkzeug>=1.0.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (2.2.2)
Requirement already satisfied: grpcio>=1.24.3 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (1.51.1)
Requirement already satisfied: protobuf<4,>=3.9.2 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (3.20.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (2.15.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (3.4.1)
Requirement already satisfied: click in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from sacremoses->transformers==4.16.2->simplet5) (8.1.3)
Requirement already satisfied: joblib in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from sacremoses->transformers==4.16.2->simplet5) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (22.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (1.8.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (1.3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (6.0.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (2.1.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (5.1.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (2.1.1)
Requirement already satisfied: zipp>=0.5 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning==1.5.10->simplet5) (3.2.2)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.5.10->simplet5) (2.8)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from datasets import load_dataset

train_dataset = load_dataset("Xenova/sponsorblock-768", split="train")


# Dataset({
#     features: ['video_index', 'video_id', 'text', 'start', 'end', 'extracted'],
#     num_rows: 334265
# })


test_dataset = load_dataset("Xenova/sponsorblock-768", split="test")


# make dataframe
train_df = train_dataset.to_pandas()
eval_df = test_dataset.to_pandas()

Using custom data configuration Xenova--sponsorblock-768-0ea5f38808e2c99d
Found cached dataset json (/home/gitpod/.cache/huggingface/datasets/Xenova___json/Xenova--sponsorblock-768-0ea5f38808e2c99d/0.0.0/e6070c77f18f01a5ad4551a8b7edfba20b8438b7cad4d94e6ad9378022ce4aab)
Using custom data configuration Xenova--sponsorblock-768-0ea5f38808e2c99d
Found cached dataset json (/home/gitpod/.cache/huggingface/datasets/Xenova___json/Xenova--sponsorblock-768-0ea5f38808e2c99d/0.0.0/e6070c77f18f01a5ad4551a8b7edfba20b8438b7cad4d94e6ad9378022ce4aab)

In [20]:
train_df.head()

,video_index,video_id,text,start,end,extracted
0,9188,-9laOYk6U8E,guys if you haven't already make sure to follo...,3.919,190.560,START_SPONSOR_TOKEN all right guys so before w...
1,64053,v-XnuiO1u2c,testing how nasty my gf is she cheating on you...,393.120,423.099,NO_SEGMENT_TOKEN
2,402,UvzzImqQ6zw,this video is sponsored by URL_TOKEN the fast ...,0.160,33.320,START_SPONSOR_TOKEN this video is sponsored by...
3,729,hnwK-nkXolc,scroll down here you can see it was designed f...,106.880,290.639,START_SPONSOR_TOKEN i'd like to thank our spon...
4,24012,Nhyb44UxWDc,nice new caldera gas station i imagine we're g...,1315.760,1324.460,NO_SEGMENT_TOKEN

In [21]:
# extract text and extracted
train_df = train_df[["text", "extracted"]]
eval_df = eval_df[["text", "extracted"]]

In [22]:
train_df.head()

,text,extracted
0,guys if you haven't already make sure to follo...,START_SPONSOR_TOKEN all right guys so before w...
1,testing how nasty my gf is she cheating on you...,NO_SEGMENT_TOKEN
2,this video is sponsored by URL_TOKEN the fast ...,START_SPONSOR_TOKEN this video is sponsored by...
3,scroll down here you can see it was designed f...,START_SPONSOR_TOKEN i'd like to thank our spon...
4,nice new caldera gas station i imagine we're g...,NO_SEGMENT_TOKEN

In [23]:
eval_df.head()

,text,extracted
0,about the sweet potato and mushrooms yeah we d...,START_SPONSOR_TOKEN about the sweet potato and...
1,test oh yeah these are gonna pass for sure thr...,START_SPONSOR_TOKEN i can't either what would ...
2,satin skirt is at a stopping point i got every...,START_SPONSOR_TOKEN native a brand that believ...
3,on today's episode of watch jericho we are bac...,NO_SEGMENT_TOKEN
4,"it's fine for most people. Look, it's snappy, ...","START_SPONSOR_TOKEN But before I do that, it's..."

In [24]:
train_df.head()

,text,extracted
0,guys if you haven't already make sure to follo...,START_SPONSOR_TOKEN all right guys so before w...
1,testing how nasty my gf is she cheating on you...,NO_SEGMENT_TOKEN
2,this video is sponsored by URL_TOKEN the fast ...,START_SPONSOR_TOKEN this video is sponsored by...
3,scroll down here you can see it was designed f...,START_SPONSOR_TOKEN i'd like to thank our spon...
4,nice new caldera gas station i imagine we're g...,NO_SEGMENT_TOKEN

In [25]:
# get first 1000 rows
train_df = train_df[:1000]
eval_df = eval_df[:100]

In [26]:
# rename columns
train_df.columns = ["source_text", "target_text"]
eval_df.columns = ["source_text", "target_text"]

# check
train_df.head()

,source_text,target_text
0,guys if you haven't already make sure to follo...,START_SPONSOR_TOKEN all right guys so before w...
1,testing how nasty my gf is she cheating on you...,NO_SEGMENT_TOKEN
2,this video is sponsored by URL_TOKEN the fast ...,START_SPONSOR_TOKEN this video is sponsored by...
3,scroll down here you can see it was designed f...,START_SPONSOR_TOKEN i'd like to thank our spon...
4,nice new caldera gas station i imagine we're g...,NO_SEGMENT_TOKEN

In [27]:
# check
eval_df.head()

,source_text,target_text
0,about the sweet potato and mushrooms yeah we d...,START_SPONSOR_TOKEN about the sweet potato and...
1,test oh yeah these are gonna pass for sure thr...,START_SPONSOR_TOKEN i can't either what would ...
2,satin skirt is at a stopping point i got every...,START_SPONSOR_TOKEN native a brand that believ...
3,on today's episode of watch jericho we are bac...,NO_SEGMENT_TOKEN
4,"it's fine for most people. Look, it's snappy, ...","START_SPONSOR_TOKEN But before I do that, it's..."

In [28]:
# import
from simplet5 import SimpleT5

# instantiate
model = SimpleT5()

# load (supports t5, mt5, byT5 models)
model.from_pretrained("t5", "t5-small")

# train
model.train(
    train_df=train_df,  # pandas dataframe with 2 columns: source_text & target_text
    eval_df=eval_df,  # pandas dataframe with 2 columns: source_text & target_text
    source_max_token_len=512,
    target_max_token_len=128,
    batch_size=8,
    max_epochs=5,
    use_gpu=False,
    outputdir="outputs",
    early_stopping_patience_epochs=0,
    precision=32,
)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs

  | Name  | Type                       | Params
-----------------------------------------------------
0 | model | T5ForConditionalGeneration | 60.5 M
-----------------------------------------------------
60.5 M    Trainable params
0         Non-trainable params
60.5 M    Total params
242.026   Total estimated model params size (MB)

Validation sanity check:   0%|          | 0/2 [00:00<?, ?it/s]

/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Global seed set to 42
/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

Epoch 0:   4%|▎         | 5/138 [07:11<3:11:14, 86.28s/it, loss=3.64, v_num=2, train_loss_step=3.430]

In [ ]:
# load trained T5 model
model.load_model("t5", "path/to/trained/model/directory", use_gpu=False)

# predict
model.predict("input text for prediction")

In [ ]:
# all code is
!pip install --upgrade pip
%pip install wheel
%pip install datasets
%pip install --upgrade simplet5
from datasets import load_dataset

train_dataset = load_dataset("Xenova/sponsorblock-768", split="train")
test_dataset = load_dataset("Xenova/sponsorblock-768", split="test")
# make dataframe
train_df = train_dataset.to_pandas()
eval_df = test_dataset.to_pandas()
# extract text and extracted
train_df = train_df[["text", "extracted"]]
eval_df = eval_df[["text", "extracted"]]
# get first 1000 rows
train_df = train_df[:1000]
eval_df = eval_df[:100]
# rename columns
train_df.columns = ["source_text", "target_text"]
eval_df.columns = ["source_text", "target_text"]
# import
from simplet5 import SimpleT5

# instantiate
model = SimpleT5()
# load (supports t5, mt5, byT5 models)
model.from_pretrained("t5", "t5-small")
# train
model.train(
    train_df=train_df,  # pandas dataframe with 2 columns: source_text & target_text
    eval_df=eval_df,  # pandas dataframe with 2 columns: source_text & target_text
    source_max_token_len=512,
    target_max_token_len=128,
    batch_size=8,
    max_epochs=5,
    use_gpu=True,
    outputdir="outputs",
    early_stopping_patience_epochs=0,
    precision=32,
)

# load trained T5 model
model.load_model("t5", "path/to/trained/model/directory", use_gpu=False)

# predict
model.predict("input text for prediction")